In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec, KeyedVectors

In [3]:
# Using Google's pretrained model to create vectors
model_path = r'E:\padhai ka saman\python\NLP\googlenews-vector-negative-300\GoogleNews-vectors-negative300.bin'
wv = KeyedVectors.load_word2vec_format(model_path, binary=True)

In [4]:
# dense vector representation of the word King with 300 dimensions (300 feature representations, embeddiing size,N = 300)
wv['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [22]:
def word_embeddings(word):
    try:
        print(f'Word Embedding for {word}:\n{wv[word]}')
    except KeyError:
        print(f"{word} not in vocabulary")

In [23]:
word_embeddings('babe')

Word Embedding for babe:
[ 0.15429688 -0.24316406 -0.0255127   0.10253906  0.0065918   0.09228516
 -0.02233887 -0.29882812 -0.08203125  0.24707031  0.03735352 -0.4453125
 -0.23828125 -0.18164062 -0.1640625   0.38476562 -0.13378906 -0.140625
 -0.07519531  0.01257324  0.02087402  0.13769531 -0.07617188 -0.12890625
  0.04589844 -0.04589844 -0.21582031  0.15820312  0.03686523 -0.30078125
  0.16699219  0.03295898  0.0324707   0.14550781 -0.34179688 -0.15917969
  0.26953125 -0.09814453  0.04467773  0.2734375  -0.16601562 -0.61328125
  0.25585938  0.03540039  0.06542969 -0.23242188  0.07714844  0.14453125
  0.27539062  0.20996094 -0.08447266  0.11865234  0.13867188 -0.10986328
  0.09179688 -0.15136719  0.10791016 -0.16992188 -0.10449219 -0.01037598
 -0.16210938  0.11572266 -0.06835938 -0.01721191  0.01623535  0.03198242
 -0.13183594  0.03833008  0.05493164  0.22070312  0.32421875  0.24316406
  0.0612793   0.28710938 -0.04467773  0.29101562 -0.00595093 -0.0018692
 -0.23730469  0.29101562 -0.32

In [5]:
wv['king'].shape

(300,)

In [6]:
# Measuring word similarity (internally uses cosine similarity)
wv.similarity('King','Queen')

0.5157251

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
cosine_similarity(wv['Honey'].reshape(1,-1),wv['Bees'].reshape(1,-1))

array([[0.2289747]], dtype=float32)

In [9]:
cosine_similarity(wv['cheetah'].reshape(1,-1),wv['leopard'].reshape(1,-1))

array([[0.62327117]], dtype=float32)

In [10]:
# Finding the most similar words
wv.most_similar('Public')

[('Pubic', 0.7086150050163269),
 ('public', 0.5893087983131409),
 ('Municipal', 0.5068287253379822),
 ('Pub_lic', 0.4839206635951996),
 ('Minister_Chalerm_Yoobamrung', 0.4774612784385681),
 ('Kathleen_Barch', 0.46767759323120117),
 ('pubic', 0.46295300126075745),
 ('Private', 0.4622167646884918),
 ('Commission_BPSC', 0.4526354670524597),
 ('Administration_DPSA', 0.4485644996166229)]

In [11]:
# The famous equation king-man+woman
wv.most_similar(positive=['king', 'woman'], negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454)]

In [12]:
# Odd one out
wv.doesnt_match(['tennis','cricket','basketball','volleyball','ludo'])

'ludo'

In [13]:
# Cosine distance between two words
wv.distance('waffle','bread')

0.5585437715053558

In [14]:
# Ranking similar words
wv.most_similar_to_given('king', ['man', 'queen', 'apple'])

'queen'

In [15]:
# Checks if word is in vocab
'dog' in wv

True

In [ ]:
# Total words in googlenews
len(wv.key_to_index)

3000000

In [ ]:
# Vocabulary of googlenews
vocab = list(wv.key_to_index.keys())
print(vocab[:200])

['</s>', 'in', 'for', 'that', 'is', 'on', '##', 'The', 'with', 'said', 'was', 'the', 'at', 'not', 'as', 'it', 'be', 'from', 'by', 'are', 'I', 'have', 'he', 'will', 'has', '####', 'his', 'an', 'this', 'or', 'their', 'who', 'they', 'but', '$', 'had', 'year', 'were', 'we', 'more', '###', 'up', 'been', 'you', 'its', 'one', 'about', 'would', 'which', 'out', 'can', 'It', 'all', 'also', 'two', 'after', 'first', 'He', 'do', 'time', 'than', 'when', 'We', 'over', 'last', 'new', 'other', 'her', 'people', 'into', 'In', 'our', 'there', 'A', 'she', 'could', 'just', 'years', 'some', 'U.S.', 'three', 'million', 'them', 'what', 'But', 'so', 'no', 'like', 'if', 'only', 'percent', 'get', 'did', 'him', 'game', 'back', 'because', 'now', '#.#', 'before', 'company', 'any', 'team', 'against', 'off', 'This', 'most', 'made', 'through', 'make', 'second', 'state', 'well', 'day', 'season', 'says', 'week', 'where', 'while', 'down', 'being', 'government', 'your', '#-#', 'home', 'going', 'my', 'good', 'They', "'re", 